project_id = "egfbyfagltzhyqlgfbpw"

[functions.flood-safety-chat]
verify_jwt = false

[functions.weather-alerts]
verify_jwt = false

[functions.flood-predict]
verify_jwt = false

[functions.send-sms-alert]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false
